[project]
name = "CardioLogAI"
version = "0.1.0"
description = "A information system based on machine learning to help in the early diagnosis of cardivascular disease"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "sqlmodel>=0.0.24",
]
